name: Run test

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grand execute permissions for gradlew
        run: chmod +x scripts/decode_google_services.sh

      - name: Create google-services.json
        env:
          FIREBASE_GOOGLE_SERVICE: ${{ secrets.FIREBASE_GOOGLE_SERVICE }}
        run: ./scripts/decode_google_services.sh

      - name: Set up environment api key
        run: echo "WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}" >> $GITHUB_ENV

      - name: Grand execute permissions for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew test